"""PlaybackAdapter protocol implemented by Enhanced/Standard/Mock adapters (spec #30)."""
from __future__ import annotations

from typing import TYPE_CHECKING, Protocol

if TYPE_CHECKING:
    from bookmark_studio.domain.equalizer import EqualizerSettings
    from bookmark_studio.playback.status import PlaybackStatus, VlcPlaylistItem


class PlaybackAdapter(Protocol):
    # Equalizer (optional): adapters without one set supports_equalizer = False, and
    # callers check it (or getattr it, for test doubles) before calling set_equalizer.
    supports_equalizer: bool
    equalizer_band_hz: tuple[float, ...]

    def connect(self) -> None: ...
    def disconnect(self) -> None: ...
    def get_status(self) -> "PlaybackStatus": ...
    def get_playlist(self) -> list["VlcPlaylistItem"]: ...
    def play(self) -> None: ...
    def pause(self) -> None: ...
    def stop(self) -> None: ...
    def next_track(self) -> None: ...
    def previous_track(self) -> None: ...
    def goto_item(self, vlc_id: int) -> None: ...
    def seek_absolute_us(self, time_us: int) -> None: ...
    def seek_relative_us(self, delta_us: int) -> None: ...
    def set_rate(self, rate: float) -> None: ...
    def set_volume(self, level: int) -> None: ...
    def set_exact_duration(self, vlc_id: int, duration_us: int | None) -> None: ...
    def set_equalizer(self, settings: "EqualizerSettings", *, full: bool = False) -> None: ...
