"""PlaybackAdapter protocol implemented by Enhanced/Standard/Mock adapters (spec #30)."""
from __future__ import annotations

from typing import Protocol, TYPE_CHECKING

if TYPE_CHECKING:
    from bookmark_studio.playback.status import PlaybackStatus, VlcPlaylistItem


class PlaybackAdapter(Protocol):
    def connect(self) -> None: ...
    def disconnect(self) -> None: ...
    def get_status(self) -> "PlaybackStatus": ...
    def get_playlist(self) -> list["VlcPlaylistItem"]: ...
    def play(self) -> None: ...
    def pause(self) -> None: ...
    def stop(self) -> None: ...
    def next_track(self) -> None: ...
    def previous_track(self) -> None: ...
    def goto_item(self, vlc_id: int) -> None: ...
    def seek_absolute_us(self, time_us: int) -> None: ...
    def seek_relative_us(self, delta_us: int) -> None: ...
    def set_rate(self, rate: float) -> None: ...
